name: "PathProbe CI (l1nuxone)"
description: "Run PathProbe harness for lab/pp-* branches"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - shell: bash
      run: |
        set -euo pipefail
        cd "${{ github.workspace }}/experiments/pathprobe"
        chmod +x probe_run.sh
        ./probe_run.sh
    - id: sanitize
      shell: bash
      run: |
        set -euo pipefail
        ref="${{ github.ref_name }}"
        safe_ref="${ref//\//-}"
        echo "ref=$safe_ref" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        name: probe-${{ steps.sanitize.outputs.ref }}
        path: experiments/pathprobe/**/probe_report.json
